apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_DATABASE
          value: utrack
        - name: MYSQL_USER
          value: test
        - name: MYSQL_PASSWORD
          value: masterkey
        - name: MYSQL_ROOT_PASSWORD
          value: rootpassword
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-initdb
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
      - name: mysql-initdb
        configMap:
          name: mysql-initdb-config
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: mysql
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
data:
  init.sql: |
    CREATE DATABASE utrack;
    USE utrack;
    CREATE TABLE usuario (
        id INT AUTO_INCREMENT PRIMARY KEY,
        email VARCHAR(255) NOT NULL
    );
    CREATE TABLE track (
        id INT AUTO_INCREMENT PRIMARY KEY,
        nome_produto VARCHAR(255),
        data_previsao DATE,
        codigo_rastreio VARCHAR(255) NOT NULL,
        codigo_usuario INT NOT NULL,
        FOREIGN KEY (codigo_usuario) REFERENCES usuario(id)
    );