CREATE DATABASE uTrack;
USE uTrack;

CREATE TABLE Client (
id INTEGER AUTO_INCREMENT PRIMARY KEY,
nome  VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL
);


CREATE TABLE Client_Track (
id INTEGER AUTO_INCREMENT PRIMARY KEY,
client INTEGER NOT NULL,
token_track VARCHAR(255) NOT NULL
);

ALTER TABLE Client_Track ADD CONSTRAINT fk_Client_Track FOREIGN KEY (client) REFERENCES Client(id) ON UPDATE CASCADE ON DELETE CASCADE;
