CREATE DATABASE uTrack;
USE uTrack;

CREATE TABLE Client (
id INTEGER AUTO_INCREMENT PRIMARY KEY,
email VARCHAR(255) NOT NULL,
token_id VARCHAR(255) NOT NULL
);


CREATE TABLE Client_Track (
id INTEGER AUTO_INCREMENT PRIMARY KEY,
client INTEGER NOT NULL,
token_track VARCHAR(255) NOT NULL,
status CHAR NOT NULL DEFAULT 'N',
data_mov DATE NOT NULL
);

ALTER TABLE Client_Track ADD CONSTRAINT fk_Client_Track FOREIGN KEY (client) REFERENCES Client(id);