CREATE DATABASE UTRACK;

USE UTRACK;

CREATE TABLE USUARIO (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(255) NOT NULL
);

CREATE TABLE TRACK (
    ID INTEGER AUTO_INCREMENT PRIMARY KEY,
    NOME_PRODUTO VARCHAR(255),
    DATAP_REVISAO DATE, 
    CODIGO_RASTREIO VARCHAR(255) NOT NULL,
    CODIGO_USUARIO INTEGER NOT NULL,
    FOREIGN KEY (CODIGO_USUARIO) REFERENCES USUARIO(ID)
);